name = input("Enter student name: ")
student_id = input("Enter student ID: ")
department = input("Enter department: ")
year = input("Enter year: ")
university = input("Enter university: ")
phone = input("Enter phone number: ")

print("\n+--------------------------------+")
print("|       AKIBA STUDENT CARD       |")
print("+--------------------------------+")
print(f"| Name: {name:}|")
print(f"| ID: {student_id:}|")
print(f"| Department: {department:}|")
print(f"| Year: {year:}|")
print(f"| University: {university:}")
print(f"| Phone: {phone:}|")
print("+--------------------------------+")